website: Remove reference to removed file
The romana file was removed in PR:
	https://github.com/metallb/metallb/pull/950

However, this reference wasn't and makes hugo fail with:
	ERROR 2021/10/06 16:12:50 [en] REF_NOT_FOUND:
	Ref "configuration/romana.md" from page
	"release-notes/_index.md": page not found

	Error: Error building site: logged 1 error(s)

This patch just removes that reference to the file that is removed.